export const HomeMenuList = [
  {
    title: "siswa",
    toPage: "SiswaPage",
    classColor: "sky",
    iconColor: "#0284c7",
    icon: "user-graduate",
  },
  {
    title: "jadwal",
    toPage: "JadwalPage",
    classColor: "green",
    iconColor: "#16a34a",
    icon: "calendar-alt",
  },
  {
    title: "transkrip",
    toPage: "TranskripPage",
    classColor: "rose",
    iconColor: "#e11d48",
    icon: "clipboard-list",
  },
  {
    title: "biaya",
    toPage: "BiayaPage",
    classColor: "amber",
    iconColor: "#d97706",
    icon: "file-invoice-dollar",
  },
  {
    title: "eskul",
    toPage: "EskulPage",
    classColor: "blue",
    iconColor: "#2563eb",
    icon: "running",
  },
  {
    title: "dosen",
    toPage: "DosenPage",
    classColor: "teal",
    iconColor: "#0d9488",
    icon: "user-tie",
  },
  {
    title: "grafik",
    toPage: "GrafikPage",
    classColor: "cyan",
    iconColor: "#0891b2",
    icon: "chart-pie",
  },
  {
    title: "jurnal",
    toPage: "JurnalPage",
    classColor: "pink",
    iconColor: "#db2777",
    icon: "book",
  },
  {
    title: "alumni",
    toPage: "AlumniPage",
    classColor: "orange",
    iconColor: "#ea580c",
    icon: "users",
  },
];
